<?php declare(strict_types=1);

namespace Rchitector\MockJson\App\Http\Controllers;

use App\Http\Controllers\Controller;
use Rchitector\MockJson\App\Generators\Simple;

class HomeController extends Controller
{
    public function index()
    {
        return view('mock-json::index');
    }

    public function json()
    {
        $data = array(
            'address' => Simple::one()->address(),
            'amPm' => Simple::one()->amPm(),
            'asciify' => Simple::one()->asciify(),
            'biasedNumberBetween' => Simple::one()->biasedNumberBetween(),
            'boolean' => Simple::one()->boolean(),
            'bothify' => Simple::one()->bothify(),
            'buildingNumber' => Simple::one()->buildingNumber(),
            'century' => Simple::one()->century(),
            'chrome' => Simple::one()->chrome(),
            'city' => Simple::one()->city(),
            'citySuffix' => Simple::one()->citySuffix(),
            'colorName' => Simple::one()->colorName(),
            'company' => Simple::one()->company(),
            'companyEmail' => Simple::one()->companyEmail(),
            'companySuffix' => Simple::one()->companySuffix(),
            'country' => Simple::one()->country(),
            'countryCode' => Simple::one()->countryCode(),
            'countryISOAlpha3' => Simple::one()->countryISOAlpha3(),
            'creditCardDetails' => Simple::one()->creditCardDetails(),
            'creditCardExpirationDate' => Simple::one()->creditCardExpirationDate(),
            'creditCardExpirationDateString' => Simple::one()->creditCardExpirationDateString(),
            'creditCardNumber' => Simple::one()->creditCardNumber(),
            'creditCardType' => Simple::one()->creditCardType(),
            'currencyCode' => Simple::one()->currencyCode(),
            'date' => Simple::one()->date(),
            'dateTime' => Simple::one()->dateTime(),
            'dateTimeAD' => Simple::one()->dateTimeAD(),
            'dateTimeBetween' => Simple::one()->dateTimeBetween(),
            'dateTimeInInterval' => Simple::one()->dateTimeInInterval(),
            'dateTimeThisCentury' => Simple::one()->dateTimeThisCentury(),
            'dateTimeThisDecade' => Simple::one()->dateTimeThisDecade(),
            'dateTimeThisMonth' => Simple::one()->dateTimeThisMonth(),
            'dateTimeThisYear' => Simple::one()->dateTimeThisYear(),
            'dayOfMonth' => Simple::one()->dayOfMonth(),
            'dayOfWeek' => Simple::one()->dayOfWeek(),
            'domainName' => Simple::one()->domainName(),
            'domainWord' => Simple::one()->domainWord(),
            'e164PhoneNumber' => Simple::one()->e164PhoneNumber(),
            'email' => Simple::one()->email(),
            'emoji' => Simple::one()->emoji(),
//            'file' => Simple::one()->file(),//->sourceDirectory('/var/www/html/tmp')->targetDirectory('/var/www/html/tmp3'),
            'firefox' => Simple::one()->firefox(),
            'firstName' => Simple::one()->firstName(),
            'firstNameFemale' => Simple::one()->firstNameFemale(),
            'firstNameMale' => Simple::one()->firstNameMale(),
            'freeEmail' => Simple::one()->freeEmail(),
            'freeEmailDomain' => Simple::one()->freeEmailDomain(),
            'getDefaultTimezone' => Simple::one()->getDefaultTimezone(),
            'hexColor' => Simple::one()->hexColor(),
            'hslColor' => Simple::one()->hslColor(),
            'hslColorAsArray' => Simple::one()->hslColorAsArray(),
            'iban' => Simple::one()->iban(),
            'image' => Simple::one()->image(),
            'imageUrl' => Simple::one()->imageUrl(),
            'imei' => Simple::one()->imei(),
            'internetExplorer' => Simple::one()->internetExplorer(),
            'iosMobileToken' => Simple::one()->iosMobileToken(),
            'ipv4' => Simple::one()->ipv4(),
            'ipv6' => Simple::one()->ipv6(),
            'iso8601' => Simple::one()->iso8601(),
            'jobTitle' => Simple::one()->jobTitle(),
            'languageCode' => Simple::one()->languageCode(),
            'lastName' => Simple::one()->lastName(),
            'latitude' => Simple::one()->latitude(),
            'lexify' => Simple::one()->lexify(),
            'linuxPlatformToken' => Simple::one()->linuxPlatformToken(),
            'linuxProcessor' => Simple::one()->linuxProcessor(),
            'localCoordinates' => Simple::one()->localCoordinates(),
            'locale' => Simple::one()->locale(),
            'localIpv4' => Simple::one()->localIpv4(),
            'longitude' => Simple::one()->longitude(),
            'macAddress' => Simple::one()->macAddress(),
            'macPlatformToken' => Simple::one()->macPlatformToken(),
            'macProcessor' => Simple::one()->macProcessor(),
            'md5' => Simple::one()->md5(),
            'month' => Simple::one()->month(),
            'monthName' => Simple::one()->monthName(),
            'msedge' => Simple::one()->msedge(),
            'name' => Simple::one()->name(),
            'numerify' => Simple::one()->numerify(),
            'opera' => Simple::one()->opera(),
            'paragraph' => Simple::one()->paragraph(),
            'paragraphs' => Simple::one()->paragraphs(),
            'passthrough' => Simple::one()->passthrough(),
            'password' => Simple::one()->password(),
            'phoneNumber' => Simple::one()->phoneNumber(),
            'postcode' => Simple::one()->postcode(),
            'randomAscii' => Simple::one()->randomAscii(),
            'randomDigitNotNull' => Simple::one()->randomDigitNotNull(),
            'randomElement' => Simple::one()->randomElement()->array(['c', 'v']),
            'randomElements' => Simple::one()->randomElements()->array(['c', 'v', 'b', 'n'])->count(3),
            'randomHtml' => Simple::one()->randomHtml(),
            'randomKey' => Simple::one()->randomKey(),
            'randomLetter' => Simple::one()->randomLetter(),
            'realText' => Simple::one()->realText(),
            'realTextBetween' => Simple::one()->realTextBetween(),
            'regexify' => Simple::one()->regexify(),
            'rgbaCssColor' => Simple::one()->rgbaCssColor(),
            'rgbColor' => Simple::one()->rgbColor(),
            'rgbColorAsArray' => Simple::one()->rgbColorAsArray(),
            'rgbCssColor' => Simple::one()->rgbCssColor(),
            'safari' => Simple::one()->safari(),
            'safeColorName' => Simple::one()->safeColorName(),
            'safeEmail' => Simple::one()->safeEmail(),
            'safeEmailDomain' => Simple::one()->safeEmailDomain(),
            'safeHexColor' => Simple::one()->safeHexColor(),
            'sentence' => Simple::one()->sentence(),
            'sentences' => Simple::one()->sentences(),
            'sha1' => Simple::one()->sha1(),
            'sha256' => Simple::one()->sha256(),
            'shuffle' => Simple::one()->shuffle(),
            'shuffleArray' => Simple::one()->shuffleArray(),
            'shuffleString' => Simple::one()->shuffleString(),
            'slug' => Simple::one()->slug(),
            'streetAddress' => Simple::one()->streetAddress(),
            'streetName' => Simple::one()->streetName(),
            'streetSuffix' => Simple::one()->streetSuffix(),
            'swiftBicNumber' => Simple::one()->swiftBicNumber(),
            'text' => Simple::one()->text(),
            'time' => Simple::one()->time(),
            'timezone' => Simple::one()->timezone(),
            'title' => Simple::one()->title(),
            'titleFemale' => Simple::one()->titleFemale(),
            'titleMale' => Simple::one()->titleMale(),
            'tld' => Simple::one()->tld(),
            'toLower' => Simple::one()->toLower(),
            'toUpper' => Simple::one()->toUpper(),
            'unixTime' => Simple::one()->unixTime(),
            'url' => Simple::one()->url(),
            'userAgent' => Simple::one()->userAgent(),
            'userName' => Simple::one()->userName(),
            'uuid' => Simple::one()->uuid(),
            'windowsPlatformToken' => Simple::one()->windowsPlatformToken(),
            'word' => Simple::one()->word(),
            'words' => Simple::one()->words(),
            'year' => Simple::one()->year(),
        );
        return response()->json($data);
    }
}
